const config = {
  brand: [
    {
      name: "Anselmo Cola",
      url: "https://www.colastufe.com/",
    },
    {
      name: "Brisach",
      url: "https://www.brisach.com/",
    },
    {
      name: "Palazzetti",
      url: "https://palazzetti.it/",
    },
    {
      name: "Cadel",
      url: "https://www.cadelsrl.com/",
    },
    {
      name: "Freepoint",
      url: "https://free-point.it/en/home-2/",
    },
    {
      name: "Last Calor",
      url: "https://www.nonsolocaldaie.it/84_last-calor",
    },
    {
      name: "MCZ",
      url: "https://www.mcz.it/it/",
    },
    {
      name: "Royal",
      url: "https://royal1915.it/",
    },
    {
      name: "Red",
      url: "https://www.redheating.fr/en/",
    },
    {
      name: "Termovana",
      url: "https://www.termovana.it/",
    },
  ],
  cities: [
    "altivole",
    "arcade",
    "asolo",
    "borso del grappa",
    "breda di piave",
    "caerano di san marco",
    "cappella maggiore",
    "carbonera",
    "casale sul sile",
    "casier",
    "castelcucco",
    "castelfranco veneto",
    "castello di godego",
    "cavaso del tomba",
    "cessalto",
    "chiarano",
    "cimadolmo",
    "cison di valmarino",
    "codognè",
    "colle umberto",
    "conegliano",
    "cordignano",
    "cornuda",
    "crocetta del montello",
    "farra di soligo",
    "follina",
    "fontanelle",
    "fonte",
    "fregona",
    "gaiarine",
    "giavera del montello",
    "godega di sant'urbano",
    "gorgo al monticano",
    "istrana",
    "loria",
    "mansuè",
    "mareno di piave",
    "maser",
    "maserada sul piave",
    "meduna di livenza",
    "miane",
    "mogliano veneto",
    "monastier di treviso",
    "monfumo",
    "montebelluna",
    "morgano",
    "moriago della battaglia",
    "motta di livenza",
    "nervesa della battaglia",
    "oderzo",
    "ormelle",
    "orsago",
    "paese",
    "pederobba",
    "pieve del grappa",
    "pieve di soligo",
    "ponte di piave",
    "ponzano veneto",
    "portobuffolé",
    "possagno",
    "povegliano",
    "preganziol",
    "quinto di treviso",
    "refrontolo",
    "resana",
    "revine lago",
    "riese pio x",
    "roncade",
    "salgareda",
    "san biagio di callalta",
    "san fior",
    "san pietro di feletto",
    "san polo di piave",
    "san vendemiano",
    "san zenone degli ezzelini",
    "santa lucia di piave",
    "sarmede",
    "segusino",
    "sernaglia della battaglia",
    "silea",
    "spresiano",
    "susegana",
    "tarzo",
    "trevignano",
    "treviso",
    "valdobbiadene",
    "vazzola",
    "vedelago",
    "vidor",
    "villorba",
    "vittorio veneto",
    "volpago del montello",
    "zenson di piave",
    "zero branco",
  ],
};

export { config };
